version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: bms_mqtt_broker
    ports:
      - "1883:1883"
    # This allows anonymous connections for easy local testing
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:2.7
    container_name: bms_telemetry_db
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Password12345
      - DOCKER_INFLUXDB_INIT_ORG=datacenter_ops
      - DOCKER_INFLUXDB_INIT_BUCKET=bms_metrics